trivy add

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -19,65 +19,65 @@ cache:
 
 ######## STAGES ########
 stages:
-  - cleanup
-  - build
-  - test
+  # - cleanup
+  # - build
+  # - test
   - scan-vulnerabilities
-  - sonar-build
-  - sonarqube-analysis_report
-  - release
-  - deploy
+#   - sonar-build
+#   - sonarqube-analysis_report
+#   - release
+#   - deploy
 
-######## CLEANUP ########
-cleanup:
-  stage: cleanup
-  tags:
-    - gitlab-lamboft-docker-runner
-  script:
-    - echo "Nettoyage des caches NuGet"
-    - dotnet nuget locals all --clear # Nettoie les caches locaux NuGet
-    - echo "Nettoyage des fichiers intermédiaires"
-    - find . -name "*.dll" -o -name "*.pdb" -o -name "*.tmp" | xargs rm -rf
+# ######## CLEANUP ########
+# cleanup:
+#   stage: cleanup
+#   tags:
+#     - gitlab-lamboft-docker-runner
+#   script:
+#     - echo "Nettoyage des caches NuGet"
+#     - dotnet nuget locals all --clear # Nettoie les caches locaux NuGet
+#     - echo "Nettoyage des fichiers intermédiaires"
+#     - find . -name "*.dll" -o -name "*.pdb" -o -name "*.tmp" | xargs rm -rf
 
 
-######## BUILD ########
-build:
-  stage: build
-  script:
-    - echo "Compilation des projets à partir de $SOLUTION_PATH"
-    - dotnet build $SOLUTION_PATH --configuration $BUILD_CONFIGURATION
-    - chmod -R 750 Authentifications/bin/  # bonne pratiques pour la securité on restreint l'accès aux binaires
-  cache:
-    key: "$CI_COMMIT_REF_NAME"
-    paths:
-      - "$NUGET_PACKAGES_DIRECTORY"
-  artifacts:
-    paths:
-      - "**/bin/**" # Artéfacts de build si nécessaire
-    expire_in: 20 minutes
+# ######## BUILD ########
+# build:
+#   stage: build
+#   script:
+#     - echo "Compilation des projets à partir de $SOLUTION_PATH"
+#     - dotnet build $SOLUTION_PATH --configuration $BUILD_CONFIGURATION
+#     - chmod -R 750 Authentifications/bin/  # bonne pratiques pour la securité on restreint l'accès aux binaires
+#   cache:
+#     key: "$CI_COMMIT_REF_NAME"
+#     paths:
+#       - "$NUGET_PACKAGES_DIRECTORY"
+#   artifacts:
+#     paths:
+#       - "**/bin/**" # Artéfacts de build si nécessaire
+#     expire_in: 20 minutes
 
-######## TEST ########
-test:
-  stage: test
-  script:
-    - echo "Exécution des tests unitaires avec collecte de couverture"
-    - dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.3.4
-    - export PATH="$PATH:/root/.dotnet/tools"
-    - TEST=$(ls | grep -o '\bTest\w*')
-    - |
-      dotnet test $TEST/$TEST.csproj \
-        --configuration $BUILD_CONFIGURATION \
-        --collect:"XPlat Code Coverage" \
-        /p:CollectCoverage=true \
-        /p:CoverletOutput=../Couverture/ \
-        /p:CoverletOutputFormat="opencover"
-    - rm -rf $TEST/TestResults
-  artifacts:
-    when: always
-    paths:
-      - $COVERAGE_REPORT_PATH
-    reports:
-      junit: $COVERAGE_REPORT_PATH
+# ######## TEST ########
+# test:
+#   stage: test
+#   script:
+#     - echo "Exécution des tests unitaires avec collecte de couverture"
+#     - dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.3.4
+#     - export PATH="$PATH:/root/.dotnet/tools"
+#     - TEST=$(ls | grep -o '\bTest\w*')
+#     - |
+#       dotnet test $TEST/$TEST.csproj \
+#         --configuration $BUILD_CONFIGURATION \
+#         --collect:"XPlat Code Coverage" \
+#         /p:CollectCoverage=true \
+#         /p:CoverletOutput=../Couverture/ \
+#         /p:CoverletOutputFormat="opencover"
+#     - rm -rf $TEST/TestResults
+#   artifacts:
+#     when: always
+#     paths:
+#       - $COVERAGE_REPORT_PATH
+#     reports:
+#       junit: $COVERAGE_REPORT_PATH
 
 before_script:
   - export $(cat .env | xargs)
@@ -100,54 +100,54 @@ scan-vulnerabilities:
 
 
 ######## SONARQUBE ########
-sonar-build:
-  stage: sonar-build
-  tags:
-    - gitlab-lamboft-shell-develop
-  variables:
-    RUNNER_TAG: "development"
-    allow_failure: true
-  script:
-    #- chmod -R 777 Couverture/
-    - echo "Lancement de l'analyse SonarQube."
-    - chmod +x sonar_check.sh; ./sonar_check.sh
-  cache:
-    policy: pull-push
-    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
-    paths:
-      - "${SONAR_USER_HOME}/cache"
-      - sonar-scanner/
-  dependencies:
-    - test # Dépend des tests et de la couverture
+# sonar-build:
+#   stage: sonar-build
+#   tags:
+#     - gitlab-lamboft-shell-develop
+#   variables:
+#     RUNNER_TAG: "development"
+#     allow_failure: true
+#   script:
+#     #- chmod -R 777 Couverture/
+#     - echo "Lancement de l'analyse SonarQube."
+#     - chmod +x sonar_check.sh; ./sonar_check.sh
+#   cache:
+#     policy: pull-push
+#     key: "sonar-cache-$CI_COMMIT_REF_SLUG"
+#     paths:
+#       - "${SONAR_USER_HOME}/cache"
+#       - sonar-scanner/
+#   dependencies:
+#     - test # Dépend des tests et de la couverture
 
-######## SONARQUBE REPORT ########
-sonarqube-analysis_report:
-  stage: sonarqube-analysis_report
-  tags:
-    - gitlab-lamboft-shell-develop
-  variables:
-    RUNNER_TAG: "development"
-    allow_failure: false
-  script:
-    - echo "Génération du rapport SonarQube."
-    - chmod +x sonar_report.sh; ./sonar_report.sh
-  dependencies:
-    - sonar-build # Dépend du build de sonar
+# ######## SONARQUBE REPORT ########
+# sonarqube-analysis_report:
+#   stage: sonarqube-analysis_report
+#   tags:
+#     - gitlab-lamboft-shell-develop
+#   variables:
+#     RUNNER_TAG: "development"
+#     allow_failure: false
+#   script:
+#     - echo "Génération du rapport SonarQube."
+#     - chmod +x sonar_report.sh; ./sonar_report.sh
+#   dependencies:
+#     - sonar-build # Dépend du build de sonar
 
-######## RELEASE ########
-release:
-  stage: release
-  tags:
-    - gitlab-lamboft-shell-develop
-  script:
-    - echo "Publication des artefacts pour le déploiement"
-    - dotnet publish $SOLUTION_PATH --configuration $BUILD_CONFIGURATION --output publish/
-  artifacts:
-    paths:
-      - publish/
-    expire_in: 1 week
-    reports:
-      dotenv: publish/.env # Optionnel : ajoutez un fichier d'environnement pour votre déploiement si nécessaire
+# ######## RELEASE ########
+# release:
+#   stage: release
+#   tags:
+#     - gitlab-lamboft-shell-develop
+#   script:
+#     - echo "Publication des artefacts pour le déploiement"
+#     - dotnet publish $SOLUTION_PATH --configuration $BUILD_CONFIGURATION --output publish/
+#   artifacts:
+#     paths:
+#       - publish/
+#     expire_in: 1 week
+#     reports:
+#       dotenv: publish/.env # Optionnel : ajoutez un fichier d'environnement pour votre déploiement si nécessaire
 
 # docker-build:
 #   script:
@@ -159,82 +159,82 @@ release:
 #     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
 #     - docker push  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
 
-######## DEPLOY ENV DEV ########
-Env_dev:
-  stage: deploy
-  tags:
-    - gitlab-lamboft-shell-develop
-  rules:
-    - if: '$CI_COMMIT_BRANCH == "develop"'
-  variables:
-    RUNNER_TAG: "development"
-    allow_failure: false
-  script:
-    - echo "DEVELOPMENT_TAG=$DEVELOPMENT_TAG" >> build.env
-    - |
-      if [[ "$DEVELOPMENT_TAG" == "true" ]]; then
-        echo "Déploiement en environnement de développement"
-        echo "Construction de l'image Docker"
-        dotnet nuget locals all --clear
-        tag=$(./image_tag.sh | tr -cd '0-9.')
-        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
-        docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag .
-        docker push  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
-        echo "Déploiement de l'image Docker"
-        PORT_NUMBER=$(grep -oP 'EXPOSE\s+\K\d+' Dockerfile)
-        docker rm -f dev-$CI_PROJECT_NAME || true
-        docker run -d -p $PORT_NUMBER:$PORT_NUMBER --name dev-$CI_PROJECT_NAME  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
-        if [ $? != 0 ]; then
-          echo "Echec de lancement du conatiner docker."
-          ./docker_cleanup.sh dev-$CI_PROJECT_NAME
-          exit 1
-        fi
-        docker network connect redis_redis dev-$CI_PROJECT_NAME
-      else
-        echo "No environment tag set for this runner development"
-        exit 1
-      fi
+# ######## DEPLOY ENV DEV ########
+# Env_dev:
+#   stage: deploy
+#   tags:
+#     - gitlab-lamboft-shell-develop
+#   rules:
+#     - if: '$CI_COMMIT_BRANCH == "develop"'
+#   variables:
+#     RUNNER_TAG: "development"
+#     allow_failure: false
+#   script:
+#     - echo "DEVELOPMENT_TAG=$DEVELOPMENT_TAG" >> build.env
+#     - |
+#       if [[ "$DEVELOPMENT_TAG" == "true" ]]; then
+#         echo "Déploiement en environnement de développement"
+#         echo "Construction de l'image Docker"
+#         dotnet nuget locals all --clear
+#         tag=$(./image_tag.sh | tr -cd '0-9.')
+#         docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
+#         docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag .
+#         docker push  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
+#         echo "Déploiement de l'image Docker"
+#         PORT_NUMBER=$(grep -oP 'EXPOSE\s+\K\d+' Dockerfile)
+#         docker rm -f dev-$CI_PROJECT_NAME || true
+#         docker run -d -p $PORT_NUMBER:$PORT_NUMBER --name dev-$CI_PROJECT_NAME  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
+#         if [ $? != 0 ]; then
+#           echo "Echec de lancement du conatiner docker."
+#           ./docker_cleanup.sh dev-$CI_PROJECT_NAME
+#           exit 1
+#         fi
+#         docker network connect redis_redis dev-$CI_PROJECT_NAME
+#       else
+#         echo "No environment tag set for this runner development"
+#         exit 1
+#       fi
 
-  artifacts:
-    reports:
-      dotenv: build.env
-    paths:
-      - .docker_tag
-    expire_in: 1 day
+#   artifacts:
+#     reports:
+#       dotenv: build.env
+#     paths:
+#       - .docker_tag
+#     expire_in: 1 day
 
-######## DEPLOY ENV STAGING #########
-Env_staging:
-  stage: deploy
-  tags:
-    - gitlab-lamboft-shell-runner
-  rules:
-    - if: '$CI_COMMIT_BRANCH == "main"'
-  script:
-    - |
-      if [[ "$STAGING_TAG" == "true" ]]; then
-        echo "Déploiement en environnement de staging"
-        echo "Construction de l'image Docker"
-        dotnet nuget locals all --clear
-        tag=$(./image_tag.sh | tr -cd '0-9.')
-        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
-        docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag .
-        docker push  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
-        echo "Déploiement de l'image Docker"
-        PORT_NUMBER=$(grep -oP 'EXPOSE\s+\K\d+' Dockerfile)
-        docker rm -f staging-$CI_PROJECT_NAME || true
-        docker run -d -p $PORT_NUMBER:$PORT_NUMBER --name staging-$CI_PROJECT_NAME  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
-        if [ $? != 0 ]; then
-          echo "Echec de lancement du conatiner docker."
-          ./docker_cleanup.sh staging-$CI_PROJECT_NAME
-          exit 1
-        fi
-      else
-        echo "No environment tag set for this runner staging"
-        exit 1
-      fi
-  artifacts:
-    reports:
-      dotenv: build.env
-    paths:
-      - .docker_tag
-    expire_in: 1 day
+# ######## DEPLOY ENV STAGING #########
+# Env_staging:
+#   stage: deploy
+#   tags:
+#     - gitlab-lamboft-shell-runner
+#   rules:
+#     - if: '$CI_COMMIT_BRANCH == "main"'
+#   script:
+#     - |
+#       if [[ "$STAGING_TAG" == "true" ]]; then
+#         echo "Déploiement en environnement de staging"
+#         echo "Construction de l'image Docker"
+#         dotnet nuget locals all --clear
+#         tag=$(./image_tag.sh | tr -cd '0-9.')
+#         docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
+#         docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag .
+#         docker push  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
+#         echo "Déploiement de l'image Docker"
+#         PORT_NUMBER=$(grep -oP 'EXPOSE\s+\K\d+' Dockerfile)
+#         docker rm -f staging-$CI_PROJECT_NAME || true
+#         docker run -d -p $PORT_NUMBER:$PORT_NUMBER --name staging-$CI_PROJECT_NAME  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
+#         if [ $? != 0 ]; then
+#           echo "Echec de lancement du conatiner docker."
+#           ./docker_cleanup.sh staging-$CI_PROJECT_NAME
+#           exit 1
+#         fi
+#       else
+#         echo "No environment tag set for this runner staging"
+#         exit 1
+#       fi
+#   artifacts:
+#     reports:
+#       dotenv: build.env
+#     paths:
+#       - .docker_tag
+#     expire_in: 1 day
