sonarQube.xml fix

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -84,8 +84,37 @@ before_script:
 
 ###### VULNERABILITIES #####
 scan-vulnerabilities:
+  image: aquasec/trivy:latest
+  stage: scan
   script:
     - dotnet list package --vulnerable
+    - | 
+      BASE_DIR="./Authentication"
+      csproj_files=$(find "$BASE_DIR" -name "*.csproj")
+
+      # Vérifier si des fichiers .csproj ont été trouvés
+      if [ -z "$csproj_files" ]; then
+        echo "Aucun fichier .csproj trouvé dans $BASE_DIR."
+        exit 0
+      fi
+        for file in $csproj_files; do
+          echo "Analyse du fichier : $file"
+          # Effectue un scan Trivy sur le répertoire contenant le fichier .csproj
+          project_dir=$(dirname "$file")
+          
+          # Trivy FS scan
+          trivy fs "$project_dir"
+          
+          # Vérification du statut
+          if [ $? -ne 0 ]; then
+            echo "Le scan pour $file a rencontré une erreur."
+          else
+            echo "Scan terminé pour $file."
+          fi
+        done
+
+        echo "Analyse complète terminée."
+  allow_failure: false
 
 ######## SONARQUBE ########
 sonar-build:
